# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: saucectl pipeline

#on: [repository_dispatch]
on:
  pull_request:
  push:
    branches:
      - main

env:
  NPM_TOKEN: ${{secrets.NPM_TOKEN}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: echo "Event '${{ github.event.action }}' received from v.113.1"
      - uses: actions/checkout@v3
        with:
          ref: do-not-check-2fa
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - name: NPM Setup
        run: |
          npm set registry "https://registry.npmjs.org/"
          npm set //registry.npmjs.org/:_authToken $NPM_TOKEN
          npm whoami
      - name: Git Setup
        run: |
          git config --global user.name "oss-sauce-bot"
          git config --global user.email "66365630+oss-sauce-bot@users.noreply.github.com"
      #- if: github.event.client_payload.version != ''
      - run: npx np "0.113.1" --no-2fa
