name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install Dependencies
        run: npm install
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test
